Test pipeline

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -75,14 +75,17 @@ jobs:
             exit 1
           fi
 
-          # Checkout the base branch with error handling
+          git fetch origin $base_branch:$base_branch || true
           git checkout $base_branch || true
 
-          # Check for checkout errors
           git status
-
+          if [[ ! -f "package.json" ]]; then
+            echo "Error: No changes in package.json!"
+            exit 1
+          fi
+          
           git add .
-          git commit -am "Update version: $version" || true  # Use the captured version
-
-          # Push the commit to the base branch
-          git push origin $base_branch --follow-tags
+          git commit -am "Update version: $version" || true
+          git checkout $base_branch
+          git push origin $base_branch --follow-tags || true
+        shell: bash
